### ISSUE TITLE
NV data mnt directory is missing with MT6768 SOC

### ISSUE THREAD

**Issue by N3vv** [FirmWire/FirmWire#7]
Hello, it is mentioned in the paper that FIRMWIRE supports the simulation of MT6768,but the following errors will be encountered when running it:
```
[INFO] firmwire.vendor.mtk.loader: Parsing debug info...
[INFO] firmwire.vendor.mtk.loader: SoC <MediaTekSOC MT6768 - 2020/04/22> (automatic)
[INFO] firmwire.vendor.mtk.loader: Loaded MTK image with 19 sections
[INFO] firmwire.vendor.mtk.loader: Loading cached MTK debug database...
[INFO] firmwire.vendor.mtk.loader: Loaded database with 49507 trace entries
[ERROR] firmwire.vendor.mtk.loader: NV data mnt directory is missing
[ERROR] firmwire.loader: Loading failed!
[ERROR] firmwire.loader: No more loaders to try
[ERROR] firmwire: Failed to load firmware
```

**Comment by mariusmue** [comment]
Heya, even though you closed the issue:

You will need the nvdata extracted from a physical phone for proper operation. By default, FirmWire expects this to be located in /mnt, but you can override this with  the `--mtk-loader-nv_data` CLI flag.

**Comment by N3vv** [comment]
> Heya, even though you closed the issue:
> 
> You will need the nvdata extracted from a physical phone for proper operation. By default, FirmWire expects this to be located in /mnt, but you can override this with the `--mtk-loader-nv_data` CLI flag.

Thank you for your patient reply!
